name: Manual Build PDF

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-pdf:
    container: ghcr.io/linuxserver/calibre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - name: configure gitbook and build pdf
      run: |
        npm i -g gitbook-cli
        gitbook install
        useradd amphineko
        chown -R amphineko $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE/src
        runuser -p -u amphineko gitbook pdf
        mv book.pdf go-for-javascript-developers.pdf
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/src/go-for-javascript-developers.pdf
