name: Manual Build PDF

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-pdf:
    container: ghcr.io/linuxserver/calibre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: |
        useradd amphineko
        chown -R amphineko $GITHUB_WORKSPACE
    - run: |
        cd $GITHUB_WORKSPACE/src/
        sudo -u amphineko "npm i -g gitbook-cli && gitbook pdf"
        ls -al
