name: Manual Build PDF

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-pdf:
    container: ghcr.io/linuxserver/calibre
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: configure gitbook
      run: |
        npm i -g gitbook-cli
        gitbook install
    - name: build pdf
      run: |
        useradd amphineko
        chown -R amphineko $GITHUB_WORKSPACE
        su amphineko -c "gitbook pdf"
        ls -al
    
